### ISSUE TITLE
running hashlink after watch won't close previous hl process

### ISSUE THREAD

**Issue by gsouf** [benmerckx/watch#4]
Hello,

I'm using watch to start a hl process after the build:

```
haxe compile.hxml -lib watch -D watch.excludeRoot -D watch.run="hl hello.hl"
```

It works well, on file save it's built again and a new hl process is executed, but it will keep the previous hl process running (in my case a windows created with heaps.io).

Is there any solution to close the process invoked with `watch.run` before running it again?

If no I'm happy to contribute

Thanks

**Comment by benmerckx** [comment]
On changes watch tries to kill the process here
https://github.com/benmerckx/watch/blob/f3596e8556b5361fc22fb6f749b56a93a5f16f8a/src/watch/Watch.hx#L171

I'm guessing it should actually try to kill the whole tree of processes that were started with run, but that is more involved. I think the implementation would look a little like this node lib: https://github.com/pkrumins/node-tree-kill/blob/cb478381547107f5c53362668533f634beff7e6e/index.js

**Comment by gsouf** [comment]
@benmerckx thank you I will investigate as soon as I have a moment
